# Data params

data:
  start_date: '1961-01-01'
  country: "us"
  horizon_in_quarters: 4
  input_files: [
    "us_4q_fred_x.csv"
    # "us_4q_oap_vw_x_stationary.csv"
  ]
  target_file: 'us_4q_fred_y.csv'
  time_steps: 12
  val_months: 24  # Number of months for early stopping
  test_months: 12 # Size of test set
  target_scale_factor: 100
  split_features: False
  split_by: 'group' # {'group', 'theme'}. 'group' splits by macro/finance
    # 'theme' splits by output, prices, ..., value, profitability, etc.

# general 
quantiles: [0.05, 0.25, 0.50, 0.75, 0.95]

# Fit params
training:
  n_estimators: 5

  fit_params:
    epochs: 500
    batch_size: 4
    shuffle: True
    verbose: 0

  # Early stopping parameters
  early_stopping:
    monitor: 'val_loss'
    min_delta: 0.001
    patience: 5
    restore_best_weights: True
    verbose: 0
  
  builder_params:
    DMQm:
      n_recurrent_layers: 2
      n_shared_layers: 2
      n_qtask_layers: 2
      n_recurrent_nodes: 32
      n_shared_nodes: 32
      n_task_nodes: 32
      initializer: 'glorot_uniform'
      lower_quantiles: [0.05, 0.25]
      upper_quantiles: [0.75, 0.95]
      loss_weights: [0.28, 0.17, 0.11, 0.17, 0.28] 
    

tuning:
  optuna_storage: 'journal'
  trials: 50
  k_folds: 10 # Number of folds for cross-validation
  val_size: 0.1 # Proportion of training data to use for validation in cross-validation

  linear_grids:
    QR:
      lr:
        type: 'float'
        values: [0.0005, 0.002]
        log_scale: true
    EN:
      l1:
        type: 'float'
        values: [0.00001, 1.0]
        log_scale: true
      l2:
        type: 'float'
        values: [0.00001, 1.0]
        log_scale: true
      lr:
        type: 'float'
        values: [0.0005, 0.002]
        log_scale: true

  dmq_grid:
    l2:
      type: 'float'
      values: [0.00001, 0.001]
      log_scale: true
    lr:
      type: 'float'
      values: [0.0005, 0.002]
      log_scale: true

  qrf_grid:
    n_estimators: [100, 500, 1000]
    max_depth: [1,2,3,4,5,6,7,8,9,10,11,12]

  qgb_grid:
    learning_rate: [0.1, 0.01, 0.001]
    n_estimators: [50, 100, 200]
    subsample: [0.25, 0.5, 1.0]
    max_depth: [1,2,3,4,5,6]

