# ========== Data Processing ==========
oap_release: 202510
construct_oap_signals: false
skip_processed_data: false
exclude_non_stationary: true
adf_significance_level: 0.05
desired_start_date_of_samples: "1961-01-01"
desired_end_date_of_samples: "2024-12-01"
initial_training_last_date: "1997-12-01"
last_date_of_sample: "2024-12-01"
remove_cols_threshold: 0.3

# OAP signal construction configurations
oap_signals:
  - signal: "avg"
    output_name: "oap_avg"
  - signal: "vw_avg"
    output_name: "oap_vw"
  - signal: "spread"
    quantiles: 10
    output_name: "oap_spread"
  - signal: 'vw_spread'
    quantiles: 10
    output_name: "oap_vw_spread"

# OAP data configurations
oap_datasets:
  - name: "oap_avg"
    file: "oap_avg.csv"
    first_difference: false
    output_name: "oap_avg_x"
  - name: "oap_avg_fd"
    file: "oap_avg.csv"
    first_difference: true
    output_name: "oap_avg_fd_x"
  # Add more OAP variants here as needed
  - name: "oap_vw"
    file: "oap_vw.csv"
    first_difference: false
    output_name: "oap_vw_x"
  - name: "oap_vw_fd"
    file: "oap_vw.csv"
    first_difference: true
    output_name: "oap_vw_fd_x"
  - name: "oap_spread"
    file: "oap_spread.csv"
    first_difference: false
    output_name: "oap_spread_x"
  - name: "oap_spread_fd"
    file: "oap_spread.csv"
    first_difference: true
    output_name: "oap_spread_fd_x"
  - name: "oap_vw_spread"
    file: "oap_vw_spread.csv"
    first_difference: true
    output_name: "oap_vw_spread_x"
