target_file: 'us_4q_fred_y.csv'
target_scale: 100
make_results: true
make_r1_tables: true
models: [
  'LIT',
  'AR1',
  'QR',
  'EN',
  # 'QPCR',
  'QRF',
  'QGB',
  # 'sDMQ',
  # 'DMQv0',
  # 'DMQv1',
  # 'DMQs',
  # 'DMQm',
  # 'DMQl',
  # 'DMQe',
  # 'sDMQm',
  # 'DMQv2c'
]
ensemble_models: [
  # 'DMQs',
  # 'DMQm', 
  # 'DMQl'
]
country: 'us'
horizon_in_quarters: 4
quantiles: [0.05, 0.25, 0.5, 0.75, 0.95]
test_start: "1998-01-01"
test_end: "2024-12-01"
start_year: 1997
end_year: 2023
concatenate_predictions: true